export const gdnStats = {
  completedProjects: 19,
  satisfiedClients: 25,
  qualifications: 95,
  experienceYears: 2,
}

export const categorizedSkills = [
  {
    categoryKey: "programmingLanguages",
    skills: [
      "JavaScript",
      "TypeScript",
      "Python",
      "Java",
      "C#",
      "C++",
      "C",
      "Go",
      "PHP",
      "Ruby",
      "Swift",
      "Kotlin",
      "Rust",
      "Dart",
      "Scala",
      "R",
      "Perl",
      "Elixir",
      "Haskell",
      "Lua",
      "Bash",
      "Shell Script",
      "Objective-C",
      "Visual Basic",
      "MATLAB",
      "Julia",
      "COBOL",
      "Fortran",
      "Assembly",
    ],
  },
  {
    categoryKey: "frontend",
    skills: [
      "React",
      "React Native",
      "Next.js",
      "Vue.js",
      "Nuxt.js",
      "Angular",
      "Svelte",
      "SvelteKit",
      "SolidJS",
      "Qwik",
      "Astro",
      "Preact",
      "Alpine.js",
      "jQuery",
      "Tailwind CSS",
      "Bootstrap",
      "Bulma",
      "Foundation",
      "Material UI",
      "Chakra UI",
      "Ant Design",
      "Styled Components",
      "Framer Motion",
    ],
  },
  {
    categoryKey: "backend",
    skills: [
      "Node.js",
      "Express.js",
      "NestJS",
      "Fastify",
      "AdonisJS",
      "Hapi",
      "Django",
      "Flask",
      "FastAPI",
      "Tornado",
      "Laravel",
      "Symfony",
      "CodeIgniter",
      "Spring Boot",
      "Micronaut",
      "Quarkus",
      "ASP.NET Core",
      "Ruby on Rails",
      "Phoenix (Elixir)",
      "Fiber (Go)",
      "Gin (Go)",
      "GraphQL",
      "REST API",
      "tRPC",
      "gRPC",
    ],
  },
  {
    categoryKey: "databases",
    skills: [
      "MySQL",
      "PostgreSQL",
      "SQLite",
      "MongoDB",
      "MariaDB",
      "Oracle",
      "Microsoft SQL Server",
      "Firebase",
      "Supabase",
      "Redis",
      "Cassandra",
      "CouchDB",
      "DynamoDB",
      "ElasticSearch",
      "PlanetScale",
      "Prisma ORM",
      "TypeORM",
      "Sequelize",
      "Mongoose",
    ],
  },
  {
    categoryKey: "devopsCloud",
    skills: [
      "Docker",
      "Kubernetes",
      "AWS",
      "Google Cloud Platform",
      "Microsoft Azure",
      "DigitalOcean",
      "Heroku",
      "Vercel",
      "Netlify",
      "Render",
      "Railway",
      "Cloudflare",
      "Terraform",
      "Ansible",
      "Jenkins",
      "GitHub Actions",
      "GitLab CI",
      "CircleCI",
      "Nginx",
      "Apache",
      "Linux",
      "Bash Scripting",
      "Serverless",
      "CI/CD",
    ],
  },
  {
    categoryKey: "designMultimedia",
    skills: [
      "Figma",
      "Adobe XD",
      "Sketch",
      "Photoshop",
      "Illustrator",
      "Premiere Pro",
      "After Effects",
      "Lightroom",
      "Canva",
      "CorelDRAW",
      "Blender",
      "Cinema 4D",
      "3ds Max",
      "Maya",
      "UI/UX Design",
      "Wireframing",
      "Prototyping",
      "Motion Graphics",
      "Video Editing",
    ],
  },
  {
    categoryKey: "marketingBusiness",
    skills: [
      "Marketing Digital",
      "SEO",
      "SEM",
      "Google Ads",
      "Facebook Ads",
      "TikTok Ads",
      "LinkedIn Ads",
      "Community Management",
      "Social Media Strategy",
      "Branding",
      "E-commerce",
      "Shopify",
      "WooCommerce",
      "Google Analytics",
      "Data Studio",
      "Email Marketing",
      "Content Marketing",
      "Copywriting",
      "Growth Hacking",
      "CRM (HubSpot, Salesforce)",
    ],
  },
  {
    categoryKey: "aiDataScience",
    skills: [
      "Machine Learning",
      "Deep Learning",
      "Artificial Intelligence",
      "Data Science",
      "Data Analysis",
      "TensorFlow",
      "PyTorch",
      "Keras",
      "Scikit-learn",
      "Pandas",
      "NumPy",
      "Matplotlib",
      "Seaborn",
      "Power BI",
      "Tableau",
      "BigQuery",
      "Apache Spark",
      "Hadoop",
      "LangChain",
      "OpenAI API",
      "IA Generativa",
    ],
  },
  {
    categoryKey: "cybersecurityTesting",
    skills: [
      "Ciberseguridad",
      "Pentesting",
      "Ethical Hacking",
      "OWASP",
      "Network Security",
      "Firewalls",
      "Testing QA",
      "Unit Testing",
      "Integration Testing",
      "Selenium",
      "Cypress",
      "Playwright",
      "Postman",
      "API Testing",
    ],
  },
  {
    categoryKey: "blockchainWeb3",
    skills: [
      "Blockchain",
      "Ethereum",
      "Solidity",
      "Web3.js",
      "Ethers.js",
      "Smart Contracts",
      "NFT",
      "DeFi",
      "Crypto Trading Bots",
      "Rust (Solana)",
      "Metamask Integration",
      "IPFS",
    ],
  },
  {
    categoryKey: "automationBots",
    skills: [
      "RPA (UiPath, Automation Anywhere)",
      "Scripting",
      "Zapier",
      "Make (Integromat)",
      "Chatbots",
      "Dialogflow",
      "Botpress",
      "Telebot",
      "Discord.js",
      "Slack Bots",
    ],
  },
  {
    categoryKey: "managementBusiness",
    skills: [
      "Scrum",
      "Agile",
      "Kanban",
      "Trello",
      "Jira",
      "Notion",
      "Asana",
      "Slack",
      "Microsoft Teams",
    ],
  },
]
