export const teamMembers = [
  {
    name: "Genderson Lora",
    position: "CEO Founder | Full-Stack Developer & Pentester",
    image: "/photo/gdn.jpeg",
    bio: "Apasionado por la innovación tecnológica, con más de 8 años de experiencia desarrollando y liderando soluciones full-stack, pentesting y transformación digital.",
    skills: ["#"],
    social: {
      linkedin: "https://www.linkedin.com/in/gdn-lr",
      dribbble: "/freelancer/genderson-lora",
      twitter: "#",
    },
  },
  {
    name: "Junior Santana",
    position: "CFO | Gestor de Finanzas",
    image: "/photo/junior.png",
    bio: "Aporta el conocimiento financiero, contable y en general una mirada analítica al negocio para tomar decisiones que minimicen riesgos y maximicen beneficios.",
    skills: ["#"],
    social: {
      linkedin: "#",
      instagram: "#",
      twitter: "#",
    },
  },
  {
    name: "Rikelvi Capellán",
    position: "CTO | Full-Stack Developer",
    image: "https://rikirilis.com/images/about-image.webp",
    bio: "Desarrollador full-stack especializado en React Native y Astro con más de 50 apps publicadas.",
    skills: [
      "React Native",
      "Astro",
      "React",
      "Node.js",
      "PostgreSQL",
      "MongoDB",
      "Docker",
      "Kubernetes",
      "AWS",
      "Azure",
      "GCP",
    ],
    social: {
      linkedin: "https://www.linkedin.com/in/rikirilis",
      github: "https://github.com/RikiRilis",
      dribbble: "https://dribbble.com/rikelvicapellan15",
    },
  },
]
