export const teamMembers = [
  {
    name: "Genderson Lora",
    position: "CEO Founder | Full-Stack Developer & Pentester",
    image: "/photo/gdn.jpeg",
    bioKey: "team.members.genderson.bio",
    skills: ["#"],
    social: {
      linkedin: "https://www.linkedin.com/in/gdn-lr",
      dribbble: "/freelancer/genderson-lora",
      twitter: "#",
    },
  },
  {
    name: "Junior Santana",
    position: "CFO | Gestor de Finanzas",
    image: "/photo/junior.png",
    bioKey: "team.members.junior.bio",
    skills: ["#"],
    social: {
      linkedin: "#",
      instagram: "#",
      twitter: "#",
    },
  },
  {
    name: "Rikelvi Capellán",
    position: "CTO | Full-Stack Developer",
    image: "https://rikirilis.com/images/about-image.webp",
    bioKey: "team.members.rikelvi.bio",
    skills: [
      "React Native",
      "Astro",
      "React",
      "Node.js",
      "PostgreSQL",
      "MongoDB",
      "Docker",
      "Kubernetes",
      "AWS",
      "Azure",
      "GCP",
    ],
    social: {
      linkedin: "https://www.linkedin.com/in/rikirilis",
      github: "https://github.com/RikiRilis",
      dribbble: "https://dribbble.com/rikelvicapellan15",
    },
  },
]
